-- Migration applied via db:push (schema.ts is the source of truth)
-- This file is kept for documentation of what changed.
--
-- Changes:
-- 1. symbols table: added scope, organization_id, prototype_id, promoted_from columns; team_id made nullable
-- 2. organizations table: added state_definitions, user_definitions JSONB columns
-- 3. Created github_team_connections table
-- 4. Created github_handoff_connections table
-- 5. Added prototypes.updated_at index
